#!/usr/bin/env python
import socket
from dns import reversename, resolver
import sys
import os
import subprocess
from optparse import OptionParser

### Create list of possible IPs 
def ipRange(start_ip, end_ip):
   start = list(map(int, start_ip.split(".")))
   end = list(map(int, end_ip.split(".")))
   temp = start
   ip_range = []
   
   ip_range.append(start_ip)
   while temp != end:
      start[3] += 1
      for i in (3, 2, 1):
         if temp[i] == 256:
            temp[i] = 0
            temp[i-1] += 1
      ip_range.append(".".join(map(str, temp)))    
     
   return ip_range

#Adding flags for command line
parser=OptionParser()
parser.add_option("-s","--showmissing",action="store_true" , dest="sm",help="Show IPs that ping back but have no DNS")
(options,args) = parser.parse_args()




start_ip = sys.argv[1]
end_ip = sys.argv[2]
ip_range = ipRange(start_ip,end_ip)
noDNS = []
noDNSyesPing=[]

# print ip_range

### Check IP list for IP without DNS
for ip in ip_range:
	try:
	     reversed_dns = socket.gethostbyaddr(ip)
	except socket.herror:
		noDNS.append(ip)

# print noDNS

### Ping IPs without DNS and print free IPs 
for i in noDNS:
	response = subprocess.call("ping " "-a " "-c " "1 " "-w " "1 " + i + " > /dev/null 2>&1 " , shell=True)	
	if response == 1 and options.sm != True:
		print i
	elif response != 1 and options.sm == True:
		print i

		


